[package]
name = "lab1"
version = "1.0.0"
authors = ["Tonman Neverwalk Alone <tonmanna@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
rand = "0.7"
lab2 = { path = "../lab2" }
lab3 = { path = "../lab3" }