[package]
name = "readfs"
version = "0.1.0"
authors = ["Worawut <tonmanna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.99"
csv = "1.1"
